spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson24
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  thymeleaf:
    suffix: .xhtml

logging:
  level:
    org:
      hibernate:
        event:
          internal:
            DefaultPersistEventListener: TRACE
