spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: qwerty
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: h2

#    url: jdbc:postgresql://localhost:5432/lesson6
#    driverClassName: org.postgresql.Driver
#    username: dalbot
#    password: imagemaster

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: error