version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend-dockerfile
    privileged: true
    ports:
      - "80:80"
    environment:
      - WAIT_FOR=backend:8080
    networks:
      - nw
  backend:
    build:
      context: .
      dockerfile: backend-dockerfile
    image: "backend"
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    networks:
      - nw
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - nw
networks:
  nw: