spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson9
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    initialization-mode: always

  h2:
    console:
      enabled: true
      path: h2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false