DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS "comments";

CREATE TABLE AUTHORS (
  id   BIGSERIAL CONSTRAINT authors_pkey PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE GENRES (
  id   BIGSERIAL  CONSTRAINT genres_pkey PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE BOOKS (
  id   BIGSERIAL CONSTRAINT books_pkey PRIMARY KEY,
  name VARCHAR(255),
  author_id BIGINT NOT NULL CONSTRAINT book_author_binding REFERENCES AUTHORS (id),
  genre_id BIGINT NOT NULL CONSTRAINT book_genre_binding REFERENCES GENRES (id)
);

CREATE TABLE "comments" (
  id   BIGSERIAL CONSTRAINT comments_pkey PRIMARY KEY,
  comment VARCHAR(255),
  book_id BIGINT NOT NULL CONSTRAINT comment_book_binding REFERENCES BOOKS (id)
);


