spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: h2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false